#!/usr/bin/env swift
//
//  punctuation_check.swift — guard for the pure-logic half of PunctuationRestorer.
//
//  Run:  swift docs/harnesses/punctuation_check.swift
//
//  WHY THIS EXISTS
//  The `JotTests` target cannot build (pre-existing FluidAudio C-module
//  resolution failure), so the strip + tokenizer logic has no unit-test home.
//  Both are load-bearing:
//
//   - `stripForModel` must preserve digit-internal separators. Before that
//     guard, "5,000" became "5 000" and "3.1" became "3 1" in 17/420 real
//     transcripts, which the model then re-punctuated as prose.
//   - `tokenize` must emit the SOURCE text of an unknown token, not the vocab
//     string. The reference implementation emits the literal "<unk>", which
//     leaked into user-visible text in 19/420 real transcripts
//     ("the front<Unk>end design skill").
//
//  MIRROR WARNING
//  The two functions below are COPIES of the ones in
//  `Jot/App/Transcription/PunctuationRestorer.swift`. Swift scripts cannot
//  import an app target. If you edit either function there, re-sync it here —
//  the same arrangement `splice_check.swift` uses.
//
//  Expectations come from `punct_fixtures.json`, generated by the Python
//  implementation that was actually evaluated
//  (docs/research/granite-turboctc/pcs.py + strip.py).

import Foundation

// MARK: - Mirrored from PunctuationRestorer.stripForModel

func stripForModel(_ text: String) -> String {
    let scalars = Array(text.lowercased())
    var out = String()
    out.reserveCapacity(scalars.count)
    for (i, ch) in scalars.enumerated() {
        if ch == "." || ch == "," {
            let prevIsDigit = i > 0 && scalars[i - 1].isNumber
            let nextIsDigit = i + 1 < scalars.count && scalars[i + 1].isNumber
            if prevIsDigit && nextIsDigit {
                out.append(ch)
                continue
            }
            out.append(" ")
            continue
        }
        if "?!;:\"()[]".contains(ch) {
            out.append(" ")
            continue
        }
        out.append(ch)
    }
    return out.split(whereSeparator: { $0 == " " || $0 == "\t" })
        .joined(separator: " ")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

// MARK: - Mirrored from PunctuationRestorer.tokenize

func tokenize(_ text: String, vocab: [String: Int], longestPiece: Int)
    -> (ids: [Int], pieces: [String]) {
    let remaining = Array("▁" + text.lowercased().replacingOccurrences(of: " ", with: "▁"))
    var ids: [Int] = []
    var pieces: [String] = []
    var cursor = 0
    while cursor < remaining.count {
        var matched = false
        let maxLen = min(longestPiece, remaining.count - cursor)
        if maxLen > 0 {
            for length in stride(from: maxLen, through: 1, by: -1) {
                let candidate = String(remaining[cursor..<(cursor + length)])
                if let id = vocab[candidate] {
                    ids.append(id); pieces.append(candidate); cursor += length
                    matched = true
                    break
                }
            }
        }
        if !matched {
            ids.append(0)                                   // UNK
            pieces.append(String(remaining[cursor]))        // pass the raw char through
            cursor += 1
        }
    }
    return (ids, pieces)
}

// MARK: - Harness

struct Fixture: Decodable {
    let input: String
    let stripped: String
    let ids: [Int]
    let pieces: [String]
}

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let fixturesURL = root.appendingPathComponent("docs/harnesses/punct_fixtures.json")
let vocabURL = root.appendingPathComponent("Jot/Resources/punct_cap_seg_vocab.json")

guard let fixturesData = try? Data(contentsOf: fixturesURL),
      let fixtures = try? JSONDecoder().decode([Fixture].self, from: fixturesData) else {
    print("FAIL: cannot read \(fixturesURL.path) — run from the repo root")
    exit(1)
}
guard let vocabData = try? Data(contentsOf: vocabURL),
      let root = try? JSONSerialization.jsonObject(with: vocabData) as? [String: Any],
      let vocab = root["vocab"] as? [String: Int] else {
    print("FAIL: cannot read \(vocabURL.path)")
    exit(1)
}
let longestPiece = vocab.keys.reduce(1) { max($0, $1.count) }

var failures = 0
for f in fixtures {
    let got = stripForModel(f.input)
    if got != f.stripped {
        failures += 1
        print("STRIP MISMATCH")
        print("   input   : \(f.input)")
        print("   expected: \(f.stripped)")
        print("   got     : \(got)")
        continue
    }
    let (ids, pieces) = tokenize(got, vocab: vocab, longestPiece: longestPiece)
    let gotIDs = Array(ids.prefix(f.ids.count))
    if gotIDs != f.ids {
        failures += 1
        print("TOKEN ID MISMATCH for: \(f.input)")
        print("   expected: \(f.ids)")
        print("   got     : \(gotIDs)")
        continue
    }
    let gotPieces = Array(pieces.prefix(f.pieces.count))
    if gotPieces != f.pieces {
        failures += 1
        print("PIECE MISMATCH for: \(f.input)")
        print("   expected: \(f.pieces)")
        print("   got     : \(gotPieces)")
    }
}

// Explicit regression assertions for the two bugs this file exists to catch.
if stripForModel("host around 5,000 pages") != "host around 5,000 pages" {
    failures += 1
    print("REGRESSION: digit-internal comma was stripped")
}
if stripForModel("gemini 3.1 flash") != "gemini 3.1 flash" {
    failures += 1
    print("REGRESSION: digit-internal period was stripped")
}
let (_, hyphenPieces) = tokenize("front-end", vocab: vocab, longestPiece: longestPiece)
if hyphenPieces.contains(where: { $0.contains("unk") }) {
    failures += 1
    print("REGRESSION: tokenizer emitted a literal <unk> instead of the source character")
}

if failures == 0 {
    print("punctuation_check: PASS (\(fixtures.count) fixtures + 3 regression assertions)")
} else {
    print("punctuation_check: \(failures) FAILURE(S)")
    exit(1)
}
